app = "crud-fruit"
primary_region = "gig"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[processes]
  app = "uvicorn project.__main__:app --host 0.0.0.0 --port 8080"

